// FROZEN after plan 02-01. Wave 2 verbs must be added via src/cli/verbs/index.ts ONLY. Do not edit this file.

import { Command, CommanderError } from 'commander';
import pc from 'picocolors';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ExitCode } from './exit-codes.js';
import { PreconditionError } from './errors.js';
import { registerVerbs } from './verbs/index.js';
import { emitError } from './output/json.js';

function readPkgVersion(): string {
  // Determine this file's directory. In CJS (tsup bin build), import.meta.url may be undefined.
  // In ESM (vitest), it is a file:// URL. Try both.
  let here: string;
  try {
    const metaUrl: string | undefined = import.meta?.url;
    if (metaUrl) {
      here = dirname(fileURLToPath(metaUrl));
    } else {
      // CJS fallback: __dirname is injected by Node CJS loader
      here = typeof __dirname === 'string' ? __dirname : process.cwd();
    }
  } catch {
    here = process.cwd();
  }

  for (const p of [
    join(here, '..', '..', 'package.json'),
    join(here, '..', '..', '..', 'package.json'),
    join(here, '..', 'package.json'),
    join(here, 'package.json'),
  ]) {
    try {
      const content: string = readFileSync(p, 'utf8');
      const parsed: unknown = JSON.parse(content);
      if (typeof parsed === 'object' && parsed !== null && 'version' in parsed) {
        const ver = (parsed as { version?: unknown }).version;
        if (typeof ver === 'string') return ver;
      }
    } catch {
      /* try next */
    }
  }
  return '0.0.0';
}

export async function runCli(argv: string[]): Promise<number> {
  const program = new Command()
    .name('auto-sop')
    .version(readPkgVersion())
    .option('--json', 'emit stable JSON output', false)
    .exitOverride();

  registerVerbs(program);

  const jsonMode = argv.includes('--json');

  try {
    await program.parseAsync(argv);
    return ExitCode.SUCCESS;
  } catch (err) {
    if (err instanceof CommanderError) {
      if (
        err.code === 'commander.version' ||
        err.code === 'commander.helpDisplayed' ||
        err.code === 'commander.help'
      ) {
        return ExitCode.SUCCESS;
      }
      const msg = err.message || 'misuse';
      if (jsonMode) emitError(ExitCode.MISUSE, msg);
      else process.stderr.write(pc.red(msg) + '\n');
      return ExitCode.MISUSE;
    }
    if (err instanceof PreconditionError) {
      if (jsonMode) emitError(ExitCode.PRECONDITION_FAILED, err.message, err.hint);
      else process.stderr.write(pc.yellow(`precondition failed: ${err.message}`) + '\n');
      return ExitCode.PRECONDITION_FAILED;
    }
    const msg = (err as Error)?.message ?? String(err);
    if (jsonMode) emitError(ExitCode.GENERIC_FAILURE, msg);
    else process.stderr.write(pc.red(`error: ${msg}`) + '\n');
    return ExitCode.GENERIC_FAILURE;
  }
}
