import { writeFileAtomic } from '../atomic/write.js';
import { promises as fs } from 'node:fs';

export interface TickScriptOpts {
  homeDir: string;
  nodeBin: string; // process.execPath at install time
  learnerJs: string; // absolute path to learner entry
  errorsLog: string; // absolute path
}

export function renderTickScript(opts: TickScriptOpts): string {
  // POSIX sh; quoted variable expansions; absolute paths baked in.
  return [
    '#!/bin/sh',
    '# claude-sop hourly tick wrapper — generated by `npx claude-sop install`',
    '# Do not edit; regenerated on every re-install.',
    '',
    'set -eu',
    '',
    '# Minimal, deterministic env',
    'export PATH="/usr/local/bin:/usr/bin:/bin:${PATH:-}"',
    `export HOME=${shellQuote(opts.homeDir)}`,
    'export CLAUDE_SOP_LEARNER=1',
    '',
    '# Absolute paths baked in at install time',
    `NODE_BIN=${shellQuote(opts.nodeBin)}`,
    `LEARNER_JS=${shellQuote(opts.learnerJs)}`,
    `ERRORS_LOG=${shellQuote(opts.errorsLog)}`,
    '',
    'mkdir -p "$(dirname "$ERRORS_LOG")"',
    '',
    '# Locking is done INSIDE the learner via proper-lockfile (macOS has no flock(1)).',
    'exec "$NODE_BIN" "$LEARNER_JS" 2>>"$ERRORS_LOG"',
    '',
  ].join('\n');
}

function shellQuote(s: string): string {
  // POSIX-safe single-quote wrapping: close, escape, reopen.
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

export async function writeTickScript(
  path: string,
  opts: TickScriptOpts,
): Promise<void> {
  await writeFileAtomic(path, renderTickScript(opts));
  await fs.chmod(path, 0o755);
}
