import { writeFileAtomic } from '../atomic/write.js';
import { promises as fs } from 'node:fs';

export interface TickScriptOpts {
  homeDir: string;
  nodeBin: string; // process.execPath at install time
  learnerJs: string; // absolute path to learner entry
  errorsLog: string; // absolute path
}

export function renderTickScript(opts: TickScriptOpts): string {
  // POSIX sh; quoted variable expansions; absolute paths baked in.
  return [
    '#!/bin/sh',
    '# auto-sop hourly tick wrapper — generated by `npx auto-sop install`',
    '# Do not edit; regenerated on every re-install.',
    '',
    'set -eu',
    '',
    '# Minimal, deterministic env',
    'export PATH="/usr/local/bin:/usr/bin:/bin:${PATH:-}"',
    `export HOME=${shellQuote(opts.homeDir)}`,
    '# Suppress Phase-2 capture inside the scheduled learner tick so it',
    '# does not record its own turns. Legacy CLAUDE_SOP_* vars are kept',
    '# for backward compat with older tick scripts still on disk.',
    'export AUTO_SOP_CAPTURE_SUPPRESS=1',
    'export CLAUDE_SOP_CAPTURE_SUPPRESS=1',
    'export CLAUDE_SOP_LEARNER=1',
    '',
    '# Absolute paths baked in at install time',
    `NODE_BIN=${shellQuote(opts.nodeBin)}`,
    `LEARNER_JS=${shellQuote(opts.learnerJs)}`,
    `ERRORS_LOG=${shellQuote(opts.errorsLog)}`,
    '',
    'mkdir -p "$(dirname "$ERRORS_LOG")"',
    '',
    '# Locking is done INSIDE the learner via proper-lockfile (macOS has no flock(1)).',
    'exec "$NODE_BIN" "$LEARNER_JS" 2>>"$ERRORS_LOG"',
    '',
  ].join('\n');
}

export function renderTickScriptCmd(opts: TickScriptOpts): string {
  // Windows .cmd batch file equivalent of the POSIX tick script.
  const dataDir = opts.homeDir.replace(/\//g, '\\') + '\\.auto-sop';
  return [
    '@echo off',
    'REM auto-sop hourly tick wrapper — generated by `npx auto-sop install`',
    'REM Do not edit; regenerated on every re-install.',
    '',
    'setlocal',
    '',
    'REM Suppress capture inside scheduled tick',
    'set AUTO_SOP_CAPTURE_SUPPRESS=1',
    'set CLAUDE_SOP_CAPTURE_SUPPRESS=1',
    'set CLAUDE_SOP_LEARNER=1',
    '',
    `set "AUTO_SOP_DATA_DIR=${dataDir}"`,
    '',
    'if not exist "%AUTO_SOP_DATA_DIR%\\logs" mkdir "%AUTO_SOP_DATA_DIR%\\logs"',
    '',
    `"${opts.nodeBin}" "${opts.learnerJs}" 2>>"${opts.errorsLog}"`,
    '',
  ].join('\r\n');
}

function shellQuote(s: string): string {
  // POSIX-safe single-quote wrapping: close, escape, reopen.
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

/**
 * Write tick script appropriate for the target platform.
 * On POSIX, sets executable permission (0o755). On Windows, skips chmod.
 */
export async function writeTickScript(
  path: string,
  opts: TickScriptOpts,
  platform: NodeJS.Platform = process.platform,
): Promise<void> {
  if (platform === 'win32') {
    await writeFileAtomic(path, renderTickScriptCmd(opts));
    // No chmod on Windows — NTFS doesn't use POSIX modes.
  } else {
    await writeFileAtomic(path, renderTickScript(opts));
    await fs.chmod(path, 0o755);
  }
}
