import { writeFileAtomic } from '../atomic/write.js';
import { getPlatform } from '../platform/index.js';

/** dirname that handles both POSIX and Windows separators regardless of host platform. */
function nodeBinDirname(nodeBin: string): string {
  const lastSep = Math.max(nodeBin.lastIndexOf('/'), nodeBin.lastIndexOf('\\'));
  return lastSep > 0 ? nodeBin.substring(0, lastSep) : '';
}

export interface TickScriptOpts {
  homeDir: string;
  nodeBin: string; // process.execPath at install time
  learnerJs: string; // absolute path to learner entry
  errorsLog: string; // absolute path
  /** Directory containing the claude binary, detected at install time. */
  claudeBinDir?: string | undefined;
}

export function renderTickScript(opts: TickScriptOpts): string {
  // POSIX sh; quoted variable expansions; absolute paths baked in.
  return [
    '#!/bin/sh',
    '# auto-sop hourly tick wrapper — generated by `npx auto-sop install`',
    '# Do not edit; regenerated on every re-install.',
    '',
    'set -eu',
    '',
    '# Minimal, deterministic env — $HOME/.local/bin always included as',
    '# safe default; detected claude binary dir inserted when available.',
    `export PATH="${buildPosixPath(opts.claudeBinDir, nodeBinDirname(opts.nodeBin))}"`,
    `export HOME=${shellQuote(opts.homeDir)}`,
    '# Suppress Phase-2 capture inside the scheduled learner tick so it',
    '# does not record its own turns. Legacy CLAUDE_SOP_* vars are kept',
    '# for backward compat with older tick scripts still on disk.',
    'export AUTO_SOP_CAPTURE_SUPPRESS=1',
    'export CLAUDE_SOP_CAPTURE_SUPPRESS=1',
    'export CLAUDE_SOP_LEARNER=1',
    '',
    '# Absolute paths baked in at install time',
    `NODE_BIN=${shellQuote(opts.nodeBin)}`,
    `LEARNER_JS=${shellQuote(opts.learnerJs)}`,
    `ERRORS_LOG=${shellQuote(opts.errorsLog)}`,
    '',
    'mkdir -p "$(dirname "$ERRORS_LOG")"',
    '',
    '# Locking is done INSIDE the learner via proper-lockfile (macOS has no flock(1)).',
    'exec "$NODE_BIN" "$LEARNER_JS" 2>>"$ERRORS_LOG"',
    '',
  ].join('\n');
}

export function renderTickScriptCmd(opts: TickScriptOpts): string {
  // Windows .cmd batch file equivalent of the POSIX tick script.
  const dataDir = opts.homeDir.replace(/\//g, '\\') + '\\.auto-sop';
  return [
    '@echo off',
    'REM auto-sop hourly tick wrapper — generated by `npx auto-sop install`',
    'REM Do not edit; regenerated on every re-install.',
    '',
    'setlocal',
    '',
    'REM Minimal, deterministic PATH',
    `set "PATH=${buildCmdPath(opts.claudeBinDir, nodeBinDirname(opts.nodeBin))}"`,
    '',
    'REM Suppress capture inside scheduled tick',
    'set AUTO_SOP_CAPTURE_SUPPRESS=1',
    'set CLAUDE_SOP_CAPTURE_SUPPRESS=1',
    'set CLAUDE_SOP_LEARNER=1',
    '',
    `set "AUTO_SOP_DATA_DIR=${dataDir}"`,
    '',
    'if not exist "%AUTO_SOP_DATA_DIR%\\logs" mkdir "%AUTO_SOP_DATA_DIR%\\logs"',
    '',
    `"${opts.nodeBin}" "${opts.learnerJs}" 2>>"${opts.errorsLog}"`,
    '',
  ].join('\r\n');
}

/**
 * Build the POSIX PATH value. Always includes $HOME/.local/bin as a safe
 * default. If claudeBinDir is provided (detected at install time), it is
 * inserted after $HOME/.local/bin. nodeBinDir (dirname of the node binary)
 * is inserted next so that npm/npx are discoverable during self-update.
 */
function buildPosixPath(claudeBinDir?: string, nodeBinDir?: string): string {
  const segments = ['$HOME/.local/bin'];
  const safeClaude = validatePathSegment(claudeBinDir);
  if (safeClaude) segments.push(safeClaude);
  const safeNode = validatePathSegment(nodeBinDir);
  if (safeNode && !segments.includes(safeNode)) segments.push(safeNode);
  segments.push('/usr/local/bin', '/usr/bin', '/bin', '${PATH:-}');
  return segments.join(':');
}

/**
 * Build the Windows CMD PATH value. Always includes %USERPROFILE%\.local\bin
 * and common Node.js install locations (%APPDATA%\npm, %LOCALAPPDATA%\Programs\nodejs).
 * If claudeBinDir is provided, it is inserted after the user-local dir.
 * nodeBinDir (dirname of node.exe) is inserted next for npm/npx discovery.
 */
function buildCmdPath(claudeBinDir?: string, nodeBinDir?: string): string {
  const segments = ['%USERPROFILE%\\.local\\bin'];
  const safeClaude = validatePathSegment(claudeBinDir);
  if (safeClaude) {
    segments.push(safeClaude.replace(/\//g, '\\'));
  }
  const safeNode = validatePathSegment(nodeBinDir);
  const safeNodeWin = safeNode?.replace(/\//g, '\\');
  if (safeNode && safeNodeWin && !segments.includes(safeNodeWin)) {
    segments.push(safeNodeWin);
  }
  // V73: Include common Node.js install locations so scheduled tasks
  // can find node.exe and npm even without the full user PATH.
  segments.push('%APPDATA%\\npm', '%LOCALAPPDATA%\\Programs\\nodejs');
  segments.push('%PATH%');
  return segments.join(';');
}

/**
 * Reject path segments containing shell-special characters that could
 * break the generated tick script. Returns the path unchanged if safe,
 * or undefined if it contains dangerous characters.
 */
export function validatePathSegment(segment: string | undefined): string | undefined {
  if (!segment) return undefined;
  // Reject paths containing shell metacharacters: " $ ` % newline null
  // Note: backslash is intentionally allowed for Windows path separators.
  // % is blocked because it triggers variable expansion in Windows CMD.
  if (/["$`%\n\0]/.test(segment)) return undefined;
  return segment;
}

function shellQuote(s: string): string {
  // POSIX-safe single-quote wrapping: close, escape, reopen.
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

/**
 * Write tick script appropriate for the target platform.
 * On POSIX, sets executable permission (0o755). On Windows, skips chmod.
 */
export async function writeTickScript(
  path: string,
  opts: TickScriptOpts,
  platform: NodeJS.Platform = process.platform,
): Promise<void> {
  if (platform === 'win32') {
    await writeFileAtomic(path, renderTickScriptCmd(opts));
    // No chmod on Windows — NTFS doesn't use POSIX modes.
  } else {
    await writeFileAtomic(path, renderTickScript(opts));
    await getPlatform().chmod(path, 0o755);
  }
}
