// AUTO-GENERATED baseline extractor for scrubber rule packs.
// Imports @secretlint/secretlint-rule-preset-recommend (devDep only) and emits
// src/scrubber/baseline.generated.ts as a TypeScript string constant.
// Deterministic: running twice produces byte-identical output.

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

/**
 * Curated baseline rule pack. Always included regardless of whether the
 * secretlint preset can be imported. Patterns are inspired by / derived from
 * @secretlint/secretlint-rule-preset-recommend (MIT, Copyright Takuto Wada
 * and contributors). See NOTICES.md for full attribution.
 */
function getCuratedBaseline(): string {
  return `version: 1
rules:
  - id: anthropic-api-key
    description: "Anthropic API key (sk-ant-*)"
    pattern: 'sk-ant-[A-Za-z0-9_\\-]{20,}'
    flags: 'g'
  - id: aws-access-key-id
    description: "AWS access key ID"
    pattern: 'AKIA[0-9A-Z]{16}'
    flags: 'g'
  - id: aws-secret-access-key
    description: "AWS secret access key (heuristic — excludes pure-hex tokens like git SHAs)"
    pattern: '(?<![A-Za-z0-9/+=])(?=[A-Za-z0-9/+=]*[A-Z])[A-Za-z0-9/+=]{40}(?![A-Za-z0-9/+=])'
    flags: 'g'
  - id: github-token
    description: "GitHub personal access / OAuth token"
    pattern: 'gh[pousr]_[A-Za-z0-9]{36,}'
    flags: 'g'
  - id: gitlab-token
    description: "GitLab personal access token"
    pattern: 'glpat-[A-Za-z0-9_\\-]{20,}'
    flags: 'g'
  - id: slack-token
    description: "Slack bot/user token"
    pattern: 'xox[baprs]-[A-Za-z0-9-]{10,}'
    flags: 'g'
  - id: stripe-key
    description: "Stripe secret/publishable key"
    pattern: '(sk|pk|rk)_(test|live)_[A-Za-z0-9]{20,}'
    flags: 'g'
  - id: jwt
    description: "JWT (three base64url-encoded segments)"
    pattern: 'eyJ[A-Za-z0-9_\\-]+\\.eyJ[A-Za-z0-9_\\-]+\\.[A-Za-z0-9_\\-]+'
    flags: 'g'
  - id: env-assignment
    description: "Environment variable assignment (KEY=VALUE)"
    pattern: '(^|\\s)([A-Z_][A-Z0-9_]{2,})=([^\\s]+)'
    flags: 'gm'
    replacement: '$1$2=[REDACTED]'
`;
}

async function main(): Promise<void> {
  const yaml = getCuratedBaseline();
  const out = resolve('src/scrubber/baseline.generated.ts');

  const banner = [
    '// AUTO-GENERATED by scripts/extract-secretlint-rules.ts — DO NOT EDIT BY HAND.',
    '// Regenerate with: npm run extract-rules',
    '// CI enforces that this file matches the extractor output (git diff --exit-code).',
    '',
    'export const BASELINE_YAML: string = `',
  ].join('\n');

  const footer = '`;\n';

  // Escape backslashes, backticks, and ${ inside the yaml to survive template literal interpretation.
  // Order matters: backslashes first, then backticks and ${.
  const escaped = yaml.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

  writeFileSync(out, banner + escaped + footer, 'utf8');
  console.log(`[extract-rules] wrote ${out}`);
}

main().catch((e: unknown) => {
  console.error(e);
  process.exit(1);
});
